root="$(cd "$(dirname "$0")/.." && pwd)"
. "$root/lib/paths.sh"
assert_eq "/h/Library/Application Support/Cursor/User" "$(HOME=/h cursor_user_dir darwin)" "darwin user_dir"
assert_eq "/h/.config/Cursor/User"                     "$(HOME=/h cursor_user_dir linux)"  "linux user_dir"
assert_eq "/h/.config/Cursor/User"                     "$(HOME=/h cursor_user_dir wsl)"    "wsl user_dir"
assert_eq "/r/Cursor/User"                             "$(APPDATA=/r cursor_user_dir windows)" "windows user_dir"
assert_eq "/h/.config/Cursor/User/rules"               "$(HOME=/h cursor_rules_dir linux)" "rules_dir"
assert_eq "/h/.config/Cursor/User/mcp.json"            "$(HOME=/h cursor_mcp_config linux)" "mcp_config"
assert_eq "/h/.config/Cursor/User/skills"              "$(HOME=/h cursor_skills_dir linux)" "skills_dir"
